name: motor
version: 0.0.1
author: Petr Hosek
description: Reimplementation of engine.io in Dart
homepage: http://github.com/petrh/motor
dependencies:
  unittest: any
  http: any
  browser: any
  benchmark_harness: '>=1.0.0 <2.0.0'
  logging: any
